FROM ghcr.io/astral-sh/uv:python3.12-trixie

RUN adduser agentbeats
USER agentbeats
RUN mkdir -p /home/agentbeats/.cache/uv
WORKDIR /home/agentbeats/naamse

COPY pyproject.toml uv.lock README.md ./
COPY src src



RUN \
    --mount=type=cache,target=/home/agentbeats/.cache/uv,uid=1000 \
    uv sync --locked

USER root
RUN apt-get update && apt-get install -y git python3-pip && \
    pip3 install gdown && \
    rm -rf /var/lib/apt/lists/*

# Download naamse.db for adversarial from Google Drive to project root
RUN gdown --fuzzy 'https://drive.google.com/file/d/1TTW9pra-VPzJI1HeWpALThNcPsAlI5x_/view?usp=sharing' -O /home/agentbeats/naamse/src/cluster_engine/data_access/adversarial/naamse.db

# Download naamse.db for benign from Google Drive to project root
RUN gdown --fuzzy 'https://drive.google.com/file/d/1unYUb7d2Tf4JJ0FbNzhCLVlsJVNtFe-7/view?usp=sharing' -O /home/agentbeats/naamse/src/cluster_engine/data_access/benign/naamse_benign.db

# Create cluster_engine directory and download files
# RUN gdown --fuzzy 'https://drive.google.com/file/d/1jtHP1v6UvUZy_5jaIJ59epVNJpUObP0U/view?usp=sharing' -O /home/agentbeats/naamse/src/cluster_engine/data_access/adversarial/embedding.npy
# RUN gdown --fuzzy 'https://drive.google.com/file/d/1YHBR8BVV68gCD3W67bHKUAXGXV2mqtKb/view?usp=sharing' -O /home/agentbeats/naamse/src/cluster_engine/data_access/adversarial/centroids.pkl

RUN chown agentbeats:agentbeats /home/agentbeats/naamse/src/cluster_engine/data_access/adversarial/naamse.db && \
    chown agentbeats:agentbeats /home/agentbeats/naamse/src/cluster_engine/data_access/benign/naamse_benign.db
    # chown agentbeats:agentbeats /home/agentbeats/naamse/src/cluster_engine/embedding.npy && \
    # chown agentbeats:agentbeats /home/agentbeats/naamse/src/cluster_engine/centroids.pkl

USER agentbeats


# Download tau2 data
# RUN git clone --depth 1 --filter=blob:none --sparse https://github.com/sierra-research/tau2-bench.git /home/agentbeats/tau2-bench && \
#     cd /home/agentbeats/tau2-bench && \
#     git sparse-checkout set data

# ENV TAU2_DATA_DIR=/home/agentbeats/tau2-bench/data

COPY scenarios scenarios

ENTRYPOINT ["uv", "run", "src/agentbeats/server.py"]
CMD ["--host", "0.0.0.0", "--port", "9009"]
EXPOSE 9009